---
pipeline:
  web:
    image: nginx:latest
    detach: true
    
  publish:
    docker:
      username: wolstena
      password: $$DOCKER_PASSWORD
      repo: wolstena/nginx-registry-proxy
      tags: [ latest, 0.0.10 ]